INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Texto Pequeno', 'tinytext', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('E-mail', 'email', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Senha', 'password', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Categoria', 'category', 'INT');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Data', 'date', 'DATETIME');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Texto Médio', 'mediumtext', 'VARCHAR(300)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Texto Grande', 'bigtext', 'TEXT');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Image', 'imagefile', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Arquivo', 'file', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Subcategoria', 'subcategory', 'INT');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('URL', 'url', 'VARCHAR(255)');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Secretarias', 'secretariats', 'INT');
INSERT INTO `modules_fields_types` (`name`, `key`, `sql_type`) VALUES ('Sim/Não', 'switch', 'INT(1)');
