<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd88e70ef5c1124f3b5912fb76f88b3b4
{
    public static $files = array (
        '37e8d069ec79e3725b00f6e962a77d70' => __DIR__ . '/../..' . '/Config.php',
    );

    public static $prefixLengthsPsr4 = array (
        '\\' => 
        array (
            '\\' => 1,
        ),
        'C' => 
        array (
            'CoffeeCode\\Router\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        '\\' => 
        array (
            0 => 'C:\\Sites\\cspsorriso.com.br admin\\server\\setup\\Resource',
        ),
        'CoffeeCode\\Router\\' => 
        array (
            0 => __DIR__ . '/..' . '/coffeecode/router/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd88e70ef5c1124f3b5912fb76f88b3b4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd88e70ef5c1124f3b5912fb76f88b3b4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd88e70ef5c1124f3b5912fb76f88b3b4::$classMap;

        }, null, ClassLoader::class);
    }
}
